[package]
name    = "foxtrot_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
triangulate = { version = "0.1", default-features = false }
step = { version = "0.1", default-features = false }

[profile.release]
panic = "unwind"
